apiVersion: v1
kind: ConfigMap
metadata:
  name: kaito-chat
data:
  TEMPERATURE: "0.9"
  AZURE_OPENAI_TYPE: ""
  AZURE_OPENAI_BASE: ""
  AZURE_OPENAI_KEY: ""
  AZURE_OPENAI_VERSION: "2024-02-01"
  AZURE_OPENAI_DEPLOYMENT: ""
  AZURE_OPENAI_MODEL: ""
  AZURE_OPENAI_SYSTEM_MESSAGE: "You are a helpful assistant."
  USE_LOCAL_LLM: "True"
  AI_ENDPOINT: "http://workspace-falcon-7b-instruct/chat"
  MAX_RETRIES: "5"
  TIMEOUT: "30"
  DEBUG: "False"